"""empty message

Revision ID: 22b4481d72c3
Revises: 75b94b8be326
Create Date: 2018-03-21 23:49:27.404388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b4481d72c3'
down_revision = '75b94b8be326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('saturated_fat', sa.Float(), nullable=True),
    sa.Column('monounsaturated_fat', sa.Float(), nullable=True),
    sa.Column('polyunsaturated_fat', sa.Float(), nullable=True),
    sa.Column('cholesterol', sa.Float(), nullable=True),
    sa.Column('carbohydrates', sa.Float(), nullable=True),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_carbohydrates'), 'ingredient', ['carbohydrates'], unique=False)
    op.create_index(op.f('ix_ingredient_cholesterol'), 'ingredient', ['cholesterol'], unique=False)
    op.create_index(op.f('ix_ingredient_description'), 'ingredient', ['description'], unique=False)
    op.create_index(op.f('ix_ingredient_fat'), 'ingredient', ['fat'], unique=False)
    op.create_index(op.f('ix_ingredient_fiber'), 'ingredient', ['fiber'], unique=False)
    op.create_index(op.f('ix_ingredient_monounsaturated_fat'), 'ingredient', ['monounsaturated_fat'], unique=False)
    op.create_index(op.f('ix_ingredient_polyunsaturated_fat'), 'ingredient', ['polyunsaturated_fat'], unique=False)
    op.create_index(op.f('ix_ingredient_protein'), 'ingredient', ['protein'], unique=False)
    op.create_index(op.f('ix_ingredient_saturated_fat'), 'ingredient', ['saturated_fat'], unique=False)
    op.create_index(op.f('ix_ingredient_sugar'), 'ingredient', ['sugar'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_sugar'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_saturated_fat'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_protein'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_polyunsaturated_fat'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_monounsaturated_fat'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_fiber'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_fat'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_description'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_cholesterol'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_carbohydrates'), table_name='ingredient')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
